### ISSUE TITLE
what is function of checkpoint ？

### ISSUE THREAD

**Issue by Johnson-yue** [rucmlcv/L2M-GAN#3]
Hi， thank you for sharing your ckpt and code,  but  I don't know  what is function of checkpoint?  man2woman  or  no smile to smile ??

**Comment by Johnson-yue** [comment]
In readme, the eval script is error    no "--mode" args

**Comment by rucmlcv** [comment]
Sorry about this error, we have corrected the script in README. We have only released the checkpoint to transfer the 'smiling' attribute by now, and more checkpoints will be released soon.

**Comment by Johnson-yue** [comment]
thanks your reply， I got it
